name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Secret Lengths
        env:
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          echo "CLIENT_ID Length: ${#CLIENT_ID}"
          echo "TENANT_ID Length: ${#TENANT_ID}"
          echo "SUBSCRIPTION_ID Length: ${#SUBSCRIPTION_ID}"
          echo "CLIENT_SECRET Length: ${#CLIENT_SECRET}"

      - name: Azure Login
        run: |
          az login --service-principal \
            --username "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

          az account set \
            --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Verify Azure Login
        run: |
          az account show

      - name: Login to ACR
        run: |
          az acr login --name shreyoshiazurecicd

      - name: Build Docker Image
        run: |
          docker build -t shreyoshiazurecicd.azurecr.io/flask-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push shreyoshiazurecicd.azurecr.io/flask-app:${{ github.sha }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group azurecicd \
            --name aks-cluster \
            --overwrite-existing

      - name: Update Deployment
        run: |
          kubectl set image deployment/flask-app \
            flask-app=shreyoshiazurecicd.azurecr.io/flask-app:${{ github.sha }}

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/flask-app
